#!/bin/bash

# get console UID
consoleuser=`/usr/bin/stat -f "%Su" /dev/console | /usr/bin/xargs /usr/bin/id -u`

/bin/launchctl bootout gui/$consoleuser /Library/LaunchAgents/com.grahamgilbert.chrome_update_notifier.plist
/bin/launchctl bootstrap gui/$consoleuser /Library/LaunchAgents/com.grahamgilbert.chrome_update_notifier.plist

exit 0
